services:
  - type: web
    name: dcf-calculator
    env: node
    buildCommand: npm run heroku-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 